# Generated by Django 4.2 on 2024-08-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name_plural': '文章栏目'},
        ),
    ]
